version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - sphinx-build -b linkcheck docs/ _build/linkcheck

sphinx:
  configuration: docs/conf.py

conda:
  environment: docs/environment_docs.yml