name: Lagrangian_diags
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - gdal
  - pyproj
  - geopandas
  - matplotlib
  - flake8>=2.1.0
  - pre_commit
  - pydocstyle
  - ipython
  - numpydoc
  - sphinx<6
  - pandoc>1.12.1,<3
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser