name: Lagrangian_diags
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - gdal
  - pyproj
  - geopandas
  - matplotlib
  - flake8>=2.1.0
  - pre_commit
  - pydocstyle
  - ipython
  - numpydoc
  - nbsphinx
  - sphinx
  - pandoc
  - pydata-sphinx-theme
  - sphinx-design
  - sphinx-autobuild
  - myst-parser
