name: Lagrangian_diags
channels:
  - conda-forge
dependencies:
  # Docs
  - ipython
  - numpydoc
  - nbsphinx
  - sphinx<6
  - pandoc>1.12.1,<3
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser