name: Lagrangian_diags
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - gdal
  - pyproj
  - geopandas
  - matplotlib

  # Docs
  - ipython
  - numpydoc
  - nbsphinx
  - sphinx<6
  - pandoc>1.12.1,<3
  - pydata-sphinx-theme
  - sphinx-autobuild
  - myst-parser